// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_uzYLIPMci4wvgQCzRRY4a_p2JbTBLmc',
    appId: '1:818668515577:android:a7cede2d35ee994d1cf228',
    messagingSenderId: '818668515577',
    projectId: 'flyingstone-wup',
    storageBucket: 'flyingstone-wup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK2UpX3UU5EAGI4Ld7ru52Lb4q35KAtWk',
    appId: '1:818668515577:ios:7720d73edb5369981cf228',
    messagingSenderId: '818668515577',
    projectId: 'flyingstone-wup',
    storageBucket: 'flyingstone-wup.appspot.com',
    androidClientId: '818668515577-re27dju1k0akf6jo7ijhsdl6sugac71s.apps.googleusercontent.com',
    iosClientId: '818668515577-s5plt389n55q3b4c48s61rrbujt4fsoa.apps.googleusercontent.com',
    iosBundleId: 'com.flstone.wup',
  );
}
